### ISSUE TITLE
Peter - New My ToDo List Live Lab with SpringBoot (Code portion)

### ISSUE THREAD

**Issue by peterrsongg** [Kuassim/Kuassim#17]
- [x] Refactor pom.xml for dependencies

- [x] Refactor deploy and build.sh
- [x] refactor Main.java to use RestController 
- [x] Change yaml for springboot
- [x] Refactor ToDoItem to use SpringData JPA
- [x] Refactor TodoItemService for Spring
- [x] Incorporate new backend with scripts
- [x] Add Swagger Config
- [x] Enable connection via Kubernetes Secret
- [x] Create DB connection with Oracle Data Source
- [x] Configure CORS
